### ISSUE TITLE
Without VPN machines how this works 

### ISSUE THREAD

**Issue by mani2care** [DJStuey/PasswordChecker#1]
Without VPN machines how do this works 

For example : 

I have one user from a remote location user machine not in office LAN or office WIFI.

user in the personal network without connected VPN during that time is this script will work ?

can you revalidate and add this VPN validation or if the case mandatory ask user to connect the VPN ?

issue 2: 
password expiry date it may depend on the organization my case I do not have any expire date haveing only when the user change the password in AD that needs to sync to the machine and immediately tell us you have changed the password in AD and you have to change the password on the machine as well 
do you have any idea about this ? can you add this validation as well ?

**Comment by HiveMindAutomation** [comment]
As this script relies on connection to the Active Directory Domain Controller, it is not possible to work without local network connection, so the VPN is a requirement.

This script is not in active development, and I'm not taking feature requests. 

You're more than welcome to fork the script and modify it to suit your needs.
